name: Test and Build

on: #Cuando se ejecuta
  push:
    branches: [ "main" ]

permissions: # Que tenga permiso de...
  contents: read # ...leer el contenido del repositorio

jobs:
  test_and_build: 
    runs-on: ubuntu-latest # Imagen de Linux que se ejecutara en un contenedor.

    steps:
    - uses: actions/checkout@v4 # Haz un checkout de la rama, es decir traer el codigo.
    - name: Set up Python 3.11
      uses: actions/setup-python@v3 # Accion de instalacion de python
      with:
        python-version: "3.11" 
    - name: Install dependencies 
      run: pip install -r src/requirements.txt
    - name: Check Linting # Hacemos linting, es decir una revision del codigo sin ejecucion para buscar problemas de estilo como imports no usados.
      working-directory: src
      run: ruff check .
    - name: Test with pytest
      working-directory: src
      run: pytest tests.py 
      
